name: phys_ed
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^4.5.0
  firebase_auth: ^6.2.0
  cloud_firestore: ^6.1.3
  firebase_storage: ^13.1.0
  flutter_riverpod: ^2.3.6
  image_picker: ^1.2.1
  http: ^1.6.0
  cached_network_image: ^3.4.1
  cupertino_icons: ^1.0.8

  # --- NEW: Offline Storage & Downloads ---
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.5
  dio: ^5.9.2
  syncfusion_flutter_pdfviewer: ^24.1.41
  video_player: ^2.8.2
  chewie: ^1.7.5
  file_picker: ^8.0.0+1
  google_sign_in: ^7.0.0
  google_sign_in_web: ^1.1.0
  open_file: ^3.5.11
  path: ^1.9.1
  mime: ^2.0.0
  supabase: ^2.10.4
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

  # --- NEW: Hive Code Generation ---
  hive_generator: ^2.0.1
  build_runner: ^2.4.8

flutter:
  uses-material-design: true
  assets:
    - assets/lnu.png
    - assets/bg.png
