// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZUiau9wSkHSE9hg4rzINCDFd_Bg_hv4A',
    appId: '1:682638053618:web:498da4c4deb9bcb26d006b',
    messagingSenderId: '682638053618',
    projectId: 'physed-2e306',
    authDomain: 'physed-2e306.firebaseapp.com',
    storageBucket: 'physed-2e306.firebasestorage.app',
    measurementId: 'G-HS4FQ2WN0F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqSZY-5D5YxBgY1FjO-DGiFRhM4u1WPK8',
    appId: '1:682638053618:android:f754988cf1d49c5d6d006b',
    messagingSenderId: '682638053618',
    projectId: 'physed-2e306',
    storageBucket: 'physed-2e306.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACyjbcaWrNXMAgQDj4wl3UDYevn5mX2LM',
    appId: '1:682638053618:ios:04c8dc521cc2f0416d006b',
    messagingSenderId: '682638053618',
    projectId: 'physed-2e306',
    storageBucket: 'physed-2e306.firebasestorage.app',
    iosBundleId: 'com.example.physEd',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACyjbcaWrNXMAgQDj4wl3UDYevn5mX2LM',
    appId: '1:682638053618:ios:04c8dc521cc2f0416d006b',
    messagingSenderId: '682638053618',
    projectId: 'physed-2e306',
    storageBucket: 'physed-2e306.firebasestorage.app',
    iosBundleId: 'com.example.physEd',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDZUiau9wSkHSE9hg4rzINCDFd_Bg_hv4A',
    appId: '1:682638053618:web:b642bb30599bf39d6d006b',
    messagingSenderId: '682638053618',
    projectId: 'physed-2e306',
    authDomain: 'physed-2e306.firebaseapp.com',
    storageBucket: 'physed-2e306.firebasestorage.app',
    measurementId: 'G-ZWEPLXVXNE',
  );
}
